version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: crypto-scout-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
      - crypto-scout

volumes:
  rabbitmq_data:

networks:
  crypto-scout:
    driver: bridge