version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: crypto-scout-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./data/rabbitmq:/var/lib/rabbitmq"
    networks:
      - crypto-scout
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  cex-client:
    build:
      context: ../cex-client
      dockerfile: Dockerfile
    container_name: crypto-scout-cex-client
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - crypto-scout
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_CONNECTION_TIMEOUT=5000
    restart: on-failure
    entrypoint: [ "/bin/sh", "-c", "sleep 10 && java -jar cex-client.jar" ]

  event-collector:
    build:
      context: ../event-collector
      dockerfile: Dockerfile
    container_name: crypto-scout-event-collector
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - crypto-scout
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_CONNECTION_TIMEOUT=5000
    restart: on-failure
    entrypoint: [ "/bin/sh", "-c", "sleep 10 && java -jar event-collector.jar" ]

networks:
  crypto-scout:
    driver: bridge