version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: crypto-scout-mq
    hostname: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
      - "5552:5552"   # Stream protocol
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - crypto-scout
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648 -rabbit vm_memory_high_watermark 0.6
      # To enable TLS, uncomment and provide certs:
      # - RABBITMQ_SSL_CACERTFILE=/certs/ca_certificate.pem
      # - RABBITMQ_SSL_CERTFILE=/certs/server_certificate.pem
      # - RABBITMQ_SSL_KEYFILE=/certs/server_key.pem
      # - RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT=true
      # - RABBITMQ_SSL_VERIFY=verify_peer
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  crypto-scout: