version: "3.9"
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - POSTGRES_DB=cryptoscout
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sa -d cryptoscout" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: