spring.application.name=cex-client
amqp.exchange.announcements=announcements.topic
logging.level.org.springframework.amqp.rabbit.core.RabbitAdmin=DEBUG
bybit.announcements.url=https://api.bybit.com/v5/announcements/index
bybit.announcements.locale=ru-RU
bybit.announcements.tags=Launchpool
bybit.announcements.types=new_crypto