# MIT License
#
# Copyright (c) 2025 Andrey Karazhev
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Server settings
server.port=8081
# RabbitMQ Connection settings
amqp.exchange.metrics=metrics-exchange
amqp.exchange.crypto=crypto-exchange
amqp.exchange.collector=collector-exchange
amqp.queue.cmc=metrics-cmc-queue
amqp.queue.bybit=metrics-bybit-queue
amqp.queue.dead=metrics-dead-letter-queue
amqp.queue.client=crypto-scout-client-queue
amqp.queue.collector=crypto-scout-collector-queue
amqp.stream.bybit=crypto-bybit-stream
amqp.queue.ttl.ms=21600000
amqp.queue.max.length=2500
amqp.stream.max.bytes=2000000000
amqp.stream.segment.bytes=100000000
amqp.rabbitmq.host=localhost
amqp.rabbitmq.port=5672
amqp.rabbitmq.username=admin
amqp.rabbitmq.password=admin

crypto-scout.bybit.batch-size=200
crypto-scout.bybit.flush-interval-ms=5000

logging.level.org.springframework.amqp.rabbit.core.RabbitAdmin=DEBUG
jdbc.datasource.url=jdbc:postgresql://localhost:5432/crypto_scout
jdbc.datasource.username=sa
jdbc.datasource.password=sa
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=crypto_scout
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
spring.jpa.hibernate.ddl-auto=none